In [1]:
a = rand(2)

2-element Array{Float64,1}:
 0.8407644738541276
 0.9485776792288316

In [7]:
file = open("Imperial College/saidas/1/dist/22.eps")

IOStream(<file Imperial College/saidas/1/dist/22.eps>)

In [8]:
a = read(file)
close(file)

In [26]:
a = reinterpret(Float16, a);

In [23]:
n = Int(sqrt(length(a)))

69

In [24]:
a = reshape(a, (n, n));

In [30]:
n = 100
a = rand(n, 2);

In [32]:
function rowWiseNorm(A)
    """
        Função para calcular a norma dos vetores linha de uma matriz
    """
    return sqrt.(sum(abs2, A, dims=2)[:, 1])
end

rowWiseNorm (generic function with 1 method)

In [36]:
function powerDecay(a::Number, b::Number, x)
    y = rowWiseNorm(x)
    return 1.0 ./ (1.0 .+ (y ./ a) .^ b)
end

powerDecay (generic function with 1 method)

In [37]:
fKernel(x) = powerDecay(1., 1.5, x)

fKernel (generic function with 1 method)

In [35]:
a'

2×100 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.0670428  0.73984   0.830615  0.887335  …  0.557727  0.402505  0.524751
 0.732297   0.818172  0.651639  0.234689     0.321574  0.651354  0.371769

In [38]:
fKernel(a .- a[1, :]')

100-element Array{Float64,1}:
 1.0
 0.641607305653876
 0.5977981678324606
 0.5155286283652875
 0.7756536626126095
 0.519802918698935
 0.9158279505925838
 0.5326685739486048
 0.7707603908669682
 0.735434559746092
 0.6546910690542145
 0.9380275047669919
 0.5633273206187993
 ⋮
 0.5464956301508184
 0.7196020852627464
 0.759721949332135
 0.5428786676155435
 0.7460996782929975
 0.8901404937361335
 0.6313366143873063
 0.8545322725724134
 0.6533303449246494
 0.6614315316598387
 0.831448246112358
 0.6921653714603561

In [42]:
aux = zeros(Float16, n, n)
for i in 1:n
    aux[i, :] += fKernel(a .- a[i, :]')
end

In [50]:
aux * aux

100×100 Array{Float16,2}:
 49.9   51.1   51.25  48.22  53.47  …  53.6   54.56  54.28  55.62  55.12
 51.1   56.88  57.0   53.1   57.72     55.25  59.44  58.25  59.06  59.0
 51.25  57.0   57.72  54.44  57.75     55.88  60.38  59.38  59.25  60.03
 48.22  53.1   54.44  53.5   53.9      53.5   58.0   57.72  55.9   58.03
 53.47  57.72  57.75  53.9   59.38     57.56  60.7   59.8   60.88  60.6
 46.84  50.5   52.0   51.75  51.62  …  52.25  55.88  56.03  54.0   56.34
 52.44  54.8   54.88  51.38  56.94     56.25  58.06  57.62  58.94  58.3
 44.88  50.6   50.88  47.2   50.88     48.47  52.72  51.44  51.88  51.9
 52.62  54.44  55.34  53.38  56.56     57.94  59.3   59.78  59.34  60.38
 56.06  60.2   61.0   58.1   61.75     61.2   64.8   64.25  64.25  65.1
 44.06  45.06  45.9   44.62  46.97  …  48.62  49.5   49.97  49.47  50.5
 53.5   55.34  55.56  52.5   57.62     57.75  59.25  59.03  59.9   59.8
 50.25  54.34  55.88  55.22  55.5      55.94  59.88  59.94  58.0   60.2
  ⋮                              